export const songs = [
  {
    title: "Starlight Serenade",
    artist: "Aurora Skies",
    album: "Celestial Echoes",
    year: 2023,
    genre: "Indie Pop",
    duration: 245, // in seconds
    trackNumber: 1,
  },
  {
    title: "Midnight Drive",
    artist: "Electric Pulse",
    album: "City Lights",
    year: 2022,
    genre: "Synthwave",
    duration: 312,
    trackNumber: 7,
  },
  {
    title: "Rustic Roads",
    artist: "Wandering Souls",
    album: "Open Horizons",
    year: 2024,
    genre: "Folk Rock",
    duration: 198,
    trackNumber: 3,
  },
  {
    title: "Crimson Tide",
    artist: "Ocean's Fury",
    album: "Deep Blue",
    year: 2021,
    genre: "Metal",
    duration: 420,
    trackNumber: 9,
  },
  {
    title: "Lunar Lullaby",
    artist: "Serene Moon",
    album: "Nightfall Whispers",
    year: 2023,
    genre: "Ambient",
    duration: 289,
    trackNumber: 2,
  },
  {
    title: "Urban Flow",
    artist: "City Beats",
    album: "Concrete Jungle",
    year: 2022,
    genre: "Hip Hop",
    duration: 276,
    trackNumber: 5,
  },
  {
    title: "Sunny Days",
    artist: "Brightside",
    album: "Summer Vibes",
    year: 2024,
    genre: "Pop",
    duration: 210,
    trackNumber: 4,
  },
  {
    title: "Distant Thunder",
    artist: "Stormwatchers",
    album: "Electric Skies",
    year: 2021,
    genre: "Rock",
    duration: 365,
    trackNumber: 8,
  },
  {
    title: "Velvet Shadows",
    artist: "Midnight Echoes",
    album: "Darkest Hour",
    year: 2023,
    genre: "Gothic Rock",
    duration: 333,
    trackNumber: 6,
  },
  {
    title: "Golden Fields",
    artist: "Harvest Sun",
    album: "Autumn Song",
    year: 2022,
    genre: "Country",
    duration: 222,
    trackNumber: 10,
  },
  {
    title: "Cosmic Dance",
    artist: "Nebula Navigators",
    album: "Infinite Expanse",
    year: 2024,
    genre: "Electronic",
    duration: 380,
    trackNumber: 11,
  },
  {
    title: "Jungle Groove",
    artist: "Wild Rhythms",
    album: "Hidden Paradise",
    year: 2023,
    genre: "Reggae",
    duration: 295,
    trackNumber: 12,
  },
  {
    title: "Piano Rain",
    artist: "Melody Drops",
    album: "Calm Before the Storm",
    year: 2023,
    genre: "Classical",
    duration: 180,
    trackNumber: 1,
  },
  {
    title: "Bass Boost",
    artist: "Frequency Kings",
    album: "Drop It",
    year: 2022,
    genre: "Dubstep",
    duration: 266,
    trackNumber: 9,
  },
  {
    title: "Saxophone Sunset",
    artist: "Smooth Notes",
    album: "Golden Hour",
    year: 2024,
    genre: "Jazz",
    duration: 201,
    trackNumber: 5,
  },
  {
    title: "Electric Dreams",
    artist: "Synth City",
    album: "Neon Nights",
    year: 2023,
    genre: "Synth Pop",
    duration: 258,
    trackNumber: 3,
  },
  {
    title: "Mountain High",
    artist: "Alpine Echoes",
    album: "Summit Sounds",
    year: 2022,
    genre: "Folk",
    duration: 214,
    trackNumber: 6,
  },
  {
    title: "Savage Beat",
    artist: "Tribal Force",
    album: "Primal Rhythm",
    year: 2024,
    genre: "Worldbeat",
    duration: 347,
    trackNumber: 11,
  },
  {
    title: "Ocean Breeze",
    artist: "Coastal Waves",
    album: "Seaside Serenade",
    year: 2021,
    genre: "Chillout",
    duration: 271,
    trackNumber: 2,
  },
  {
    title: "City Lights",
    artist: "Urban Pulse",
    album: "Metropolis",
    year: 2023,
    genre: "House",
    duration: 302,
    trackNumber: 8,
  },
  {
    title: "Retrograde",
    artist: "Astro Horizon",
    album: "Celestial Bodies",
    year: 2022,
    genre: "Space Rock",
    duration: 412,
    trackNumber: 7,
  },
  {
    title: "Silent Storm",
    artist: "Dark Tranquility",
    album: "Edge of Twilight",
    year: 2023,
    genre: "Dark Ambient",
    duration: 320,
    trackNumber: 12,
  },
  {
    title: "Funky Town",
    artist: "Groove Masters",
    album: "Soul Train",
    year: 2024,
    genre: "Funk",
    duration: 245,
    trackNumber: 4,
  },
  {
    title: "Celtic Fire",
    artist: "Emerald Isles",
    album: "Ancient Magic",
    year: 2021,
    genre: "Celtic Folk",
    duration: 288,
    trackNumber: 10,
  },
  {
    title: "Ragtime Blues",
    artist: "Mississippi Mud",
    album: "Riverboat Shuffle",
    year: 2022,
    genre: "Blues",
    duration: 230,
    trackNumber: 1,
  },
  {
    title: "Indie Anthem",
    artist: "The Outsiders",
    album: "Generation X",
    year: 2023,
    genre: "Indie Rock",
    duration: 298,
    trackNumber: 7,
  },
  {
    title: "Dream Weaver",
    artist: "Lullaby Lane",
    album: "Sweet Slumber",
    year: 2024,
    genre: "New Age",
    duration: 315,
    trackNumber: 2,
  },
  {
    title: "Power Surge",
    artist: "Voltage",
    album: "High Energy",
    year: 2022,
    genre: "Industrial",
    duration: 350,
    trackNumber: 9,
  },
  {
    title: "Tropical Rain",
    artist: "Rainforest Collective",
    album: "Amazonia",
    year: 2021,
    genre: "World",
    duration: 260,
    trackNumber: 5,
  },
  {
    title: "Space Odyssey",
    artist: "Starship Symphony",
    album: "Beyond the Stars",
    year: 2023,
    genre: "Experimental",
    duration: 400,
    trackNumber: 11,
  },
];
